### ISSUE TITLE
These dependencies were not found

### ISSUE THREAD

**Issue by ahmedOumezzine** [d-levin/quasar-server-side-data-table#1]
Hello my friend, I try to use your solution in my project but I think you have the same dependencies that you can not find, you can check please.

-------------------------------------------------
**Message error from console** 
 ERROR  Failed to compile with 2 errors   

These dependencies were not found:

* src/filters/titleize in ./src/components/default-config.js
* src/utils/object-utils in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/ServerSideDataTable.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save src/filters/titleize src/utils/object-utils
Terminate batch job (Y/N)? y

C:\Users\xxxxx\source\repos\VuejsApp\VuejsApp>npm install --save src/filters/titleize src/utils/object-utils
npm ERR! code ENOLOCAL
npm ERR! Could not install from "src\filters\titleize" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxx\AppData\Roaming\npm-cache\_logs\2019-11-08T23_03_08_588Z-debug.log

**Comment by d-levin** [comment]
@ahmedOumezzine This is a very old project and I wouldn't recommend using it in any new applications. I doubt it's compatible with the latest Quasar Framework.

If you still want to use it then it should be fine if you just removed the missing dependencies and rewrote some of the code to exclude them.
